version: "3.8"

services:
  backend:
    image: jereprograma/le-dance-backend:latest  # Imagen desde Docker Hub
    container_name: le-dance-backend
    restart: always
    ports:
      - "8080:8080"  # Backend: Contenedor expone 8080, se mapea al 8080 del host.
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ledance_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  frontend:
    image: jereprograma/le-dance-frontend:latest  # Imagen desde Docker Hub
    container_name: le-dance-frontend
    restart: always
    ports:
      - "8081:80"    # Frontend: Contenedor expone 80, se mapea al 8081 del host.
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: le-dance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ledance_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

