-- Baseline canónica de Le Dance. Requiere un esquema public vacío.
-- El esquema heredado V1-V060 sólo se conserva en Git, commit
-- 2764083a47303880b2e90dc6bcef807406b3ee32.

CREATE TABLE public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(50) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_roles_descripcion UNIQUE (descripcion)
);

CREATE TABLE public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(100) NOT NULL,
    contrasena VARCHAR(100) NOT NULL,
    rol_id BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_usuarios_rol FOREIGN KEY (rol_id) REFERENCES public.roles(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_usuarios_nombre_normalizado
    ON public.usuarios (lower(nombre_usuario));
CREATE INDEX ix_usuarios_rol ON public.usuarios (rol_id);

CREATE TABLE public.alumnos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    fecha_nacimiento DATE,
    celular1 VARCHAR(30),
    celular2 VARCHAR(30),
    email VARCHAR(254),
    documento VARCHAR(30),
    cuit VARCHAR(20),
    fecha_incorporacion DATE NOT NULL,
    fecha_de_baja DATE,
    nombre_padres VARCHAR(200),
    autorizado_para_salir_solo BOOLEAN,
    otras_notas TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_alumnos_baja CHECK ((activo AND fecha_de_baja IS NULL) OR NOT activo)
);

CREATE UNIQUE INDEX uq_alumnos_documento
    ON public.alumnos (documento) WHERE documento IS NOT NULL;
CREATE INDEX ix_alumnos_activos_nombre
    ON public.alumnos (activo, apellido, nombre);

CREATE TABLE public.salones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_salones_nombre UNIQUE (nombre)
);

CREATE TABLE public.profesores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    telefono VARCHAR(30),
    usuario_id BIGINT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_profesores_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_profesores_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE TABLE public.observaciones_profesores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    observacion TEXT NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_observaciones_profesor FOREIGN KEY (profesor_id) REFERENCES public.profesores(id) ON DELETE RESTRICT
);

CREATE INDEX ix_observaciones_profesor_fecha
    ON public.observaciones_profesores (profesor_id, fecha);

CREATE TABLE public.bonificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(150) NOT NULL,
    porcentaje_descuento NUMERIC(7,4) NOT NULL DEFAULT 0,
    valor_fijo NUMERIC(19,2) NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    observaciones VARCHAR(500),
    CONSTRAINT uq_bonificaciones_descripcion UNIQUE (descripcion),
    CONSTRAINT ck_bonificaciones_porcentaje CHECK (porcentaje_descuento BETWEEN 0 AND 100),
    CONSTRAINT ck_bonificaciones_valor CHECK (valor_fijo >= 0)
);

CREATE TABLE public.recargos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(150) NOT NULL,
    porcentaje NUMERIC(7,4) NOT NULL DEFAULT 0,
    valor_fijo NUMERIC(19,2) NOT NULL DEFAULT 0,
    dia_del_mes_aplicacion INTEGER,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_recargos_descripcion UNIQUE (descripcion),
    CONSTRAINT ck_recargos_porcentaje CHECK (porcentaje BETWEEN 0 AND 100),
    CONSTRAINT ck_recargos_valor CHECK (valor_fijo >= 0),
    CONSTRAINT ck_recargos_dia CHECK (dia_del_mes_aplicacion IS NULL OR dia_del_mes_aplicacion BETWEEN 1 AND 31)
);

CREATE TABLE public.metodo_pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    recargo NUMERIC(7,4) NOT NULL DEFAULT 0,
    CONSTRAINT uq_metodos_pago_descripcion UNIQUE (descripcion),
    CONSTRAINT ck_metodos_pago_recargo CHECK (recargo BETWEEN 0 AND 100)
);

CREATE TABLE public.sub_conceptos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(150) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_sub_conceptos_descripcion UNIQUE (descripcion)
);

CREATE TABLE public.conceptos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(150) NOT NULL,
    precio NUMERIC(19,2) NOT NULL,
    sub_concepto_id BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_conceptos_precio CHECK (precio >= 0),
    CONSTRAINT uq_conceptos_sub_descripcion UNIQUE (sub_concepto_id, descripcion),
    CONSTRAINT fk_conceptos_sub_concepto FOREIGN KEY (sub_concepto_id) REFERENCES public.sub_conceptos(id) ON DELETE RESTRICT
);

CREATE INDEX ix_conceptos_sub_concepto ON public.conceptos (sub_concepto_id);

CREATE TABLE public.stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    precio NUMERIC(19,2) NOT NULL,
    cantidad_actual INTEGER NOT NULL DEFAULT 0,
    requiere_control_de_stock BOOLEAN NOT NULL DEFAULT TRUE,
    codigo_barras VARCHAR(100),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_stocks_nombre UNIQUE (nombre),
    CONSTRAINT ck_stocks_precio CHECK (precio >= 0),
    CONSTRAINT ck_stocks_cantidad CHECK (cantidad_actual >= 0)
);

CREATE UNIQUE INDEX uq_stocks_codigo_barras
    ON public.stocks (codigo_barras) WHERE codigo_barras IS NOT NULL;
CREATE INDEX ix_stocks_activos_nombre ON public.stocks (activo, nombre);

CREATE TABLE public.disciplinas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    salon_id BIGINT,
    profesor_id BIGINT NOT NULL,
    valor_cuota NUMERIC(19,2) NOT NULL,
    matricula NUMERIC(19,2) NOT NULL DEFAULT 0,
    clase_suelta NUMERIC(19,2) NOT NULL DEFAULT 0,
    clase_prueba NUMERIC(19,2) NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_disciplinas_valor_cuota CHECK (valor_cuota >= 0),
    CONSTRAINT ck_disciplinas_matricula CHECK (matricula >= 0),
    CONSTRAINT ck_disciplinas_clase_suelta CHECK (clase_suelta >= 0),
    CONSTRAINT ck_disciplinas_clase_prueba CHECK (clase_prueba >= 0),
    CONSTRAINT fk_disciplinas_salon FOREIGN KEY (salon_id) REFERENCES public.salones(id) ON DELETE RESTRICT,
    CONSTRAINT fk_disciplinas_profesor FOREIGN KEY (profesor_id) REFERENCES public.profesores(id) ON DELETE RESTRICT
);

CREATE INDEX ix_disciplinas_salon ON public.disciplinas (salon_id);
CREATE INDEX ix_disciplinas_profesor ON public.disciplinas (profesor_id);
CREATE INDEX ix_disciplinas_activo_nombre ON public.disciplinas (activo, nombre);

CREATE TABLE public.disciplina_horarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id BIGINT NOT NULL,
    dia_semana VARCHAR(12) NOT NULL,
    horario_inicio TIME NOT NULL,
    duracion NUMERIC(5,2) NOT NULL,
    CONSTRAINT ck_horarios_dia CHECK (dia_semana IN ('LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO')),
    CONSTRAINT ck_horarios_duracion CHECK (duracion > 0),
    CONSTRAINT uq_horarios_disciplina UNIQUE (disciplina_id, dia_semana, horario_inicio),
    CONSTRAINT fk_horarios_disciplina FOREIGN KEY (disciplina_id) REFERENCES public.disciplinas(id) ON DELETE CASCADE
);

CREATE TABLE public.inscripciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL,
    disciplina_id BIGINT NOT NULL,
    bonificacion_id BIGINT,
    fecha_inscripcion DATE NOT NULL,
    fecha_baja DATE,
    estado VARCHAR(12) NOT NULL DEFAULT 'ACTIVA',
    costo_particular NUMERIC(19,2),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_inscripciones_estado CHECK (estado IN ('ACTIVA','INACTIVA','FINALIZADA')),
    CONSTRAINT ck_inscripciones_costo CHECK (costo_particular IS NULL OR costo_particular >= 0),
    CONSTRAINT ck_inscripciones_baja CHECK ((estado = 'ACTIVA' AND fecha_baja IS NULL) OR estado IN ('INACTIVA','FINALIZADA')),
    CONSTRAINT fk_inscripciones_alumno FOREIGN KEY (alumno_id) REFERENCES public.alumnos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_inscripciones_disciplina FOREIGN KEY (disciplina_id) REFERENCES public.disciplinas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_inscripciones_bonificacion FOREIGN KEY (bonificacion_id) REFERENCES public.bonificaciones(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX uq_inscripciones_activas
    ON public.inscripciones (alumno_id, disciplina_id) WHERE estado = 'ACTIVA';
CREATE INDEX ix_inscripciones_alumno_estado ON public.inscripciones (alumno_id, estado);
CREATE INDEX ix_inscripciones_disciplina_estado ON public.inscripciones (disciplina_id, estado);
CREATE INDEX ix_inscripciones_bonificacion ON public.inscripciones (bonificacion_id);

CREATE TABLE public.mensualidades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id BIGINT NOT NULL,
    bonificacion_id BIGINT,
    recargo_id BIGINT,
    anio INTEGER NOT NULL,
    mes INTEGER NOT NULL,
    fecha_generacion DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'EMITIDA',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_mensualidades_anio CHECK (anio BETWEEN 2000 AND 9999),
    CONSTRAINT ck_mensualidades_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_mensualidades_estado CHECK (estado IN ('EMITIDA','ANULADA')),
    CONSTRAINT uq_mensualidades_periodo UNIQUE (inscripcion_id, anio, mes),
    CONSTRAINT fk_mensualidades_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES public.inscripciones(id) ON DELETE RESTRICT,
    CONSTRAINT fk_mensualidades_bonificacion FOREIGN KEY (bonificacion_id) REFERENCES public.bonificaciones(id) ON DELETE RESTRICT,
    CONSTRAINT fk_mensualidades_recargo FOREIGN KEY (recargo_id) REFERENCES public.recargos(id) ON DELETE RESTRICT
);

CREATE INDEX ix_mensualidades_bonificacion ON public.mensualidades (bonificacion_id);
CREATE INDEX ix_mensualidades_recargo ON public.mensualidades (recargo_id);
CREATE INDEX ix_mensualidades_vencimiento ON public.mensualidades (fecha_vencimiento, estado);

CREATE TABLE public.matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL,
    anio INTEGER NOT NULL,
    fecha_emision DATE NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'EMITIDA',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_matriculas_anio CHECK (anio BETWEEN 2000 AND 9999),
    CONSTRAINT ck_matriculas_estado CHECK (estado IN ('EMITIDA','ANULADA')),
    CONSTRAINT uq_matriculas_periodo UNIQUE (alumno_id, anio),
    CONSTRAINT fk_matriculas_alumno FOREIGN KEY (alumno_id) REFERENCES public.alumnos(id) ON DELETE RESTRICT
);

CREATE TABLE public.asistencias_mensuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciplina_id BIGINT NOT NULL,
    mes INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    CONSTRAINT ck_asistencias_mensuales_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_asistencias_mensuales_anio CHECK (anio BETWEEN 2000 AND 9999),
    CONSTRAINT uq_asistencias_mensuales_periodo UNIQUE (disciplina_id, anio, mes),
    CONSTRAINT fk_asistencias_mensuales_disciplina FOREIGN KEY (disciplina_id) REFERENCES public.disciplinas(id) ON DELETE RESTRICT
);

CREATE TABLE public.asistencias_alumno_mensual (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id BIGINT NOT NULL,
    asistencia_mensual_id BIGINT NOT NULL,
    observacion VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_asistencia_alumno_periodo UNIQUE (asistencia_mensual_id, inscripcion_id),
    CONSTRAINT fk_asistencia_alumno_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES public.inscripciones(id) ON DELETE RESTRICT,
    CONSTRAINT fk_asistencia_alumno_mensual FOREIGN KEY (asistencia_mensual_id) REFERENCES public.asistencias_mensuales(id) ON DELETE RESTRICT
);

CREATE INDEX ix_asistencia_alumno_inscripcion
    ON public.asistencias_alumno_mensual (inscripcion_id);

CREATE TABLE public.asistencias_diarias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asistencia_alumno_mensual_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    estado VARCHAR(10) NOT NULL,
    vigente BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_asistencias_diarias_estado CHECK (estado IN ('PRESENTE','AUSENTE','JUSTIFICADO')),
    CONSTRAINT uq_asistencias_diarias_fecha UNIQUE (asistencia_alumno_mensual_id, fecha),
    CONSTRAINT fk_asistencias_diarias_alumno FOREIGN KEY (asistencia_alumno_mensual_id) REFERENCES public.asistencias_alumno_mensual(id) ON DELETE RESTRICT
);

CREATE TABLE public.ventas_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL,
    stock_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(19,2) NOT NULL,
    fecha DATE NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'REGISTRADA',
    idempotency_key VARCHAR(100) NOT NULL,
    reversal_idempotency_key VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_ventas_stock_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_ventas_stock_precio CHECK (precio_unitario >= 0),
    CONSTRAINT ck_ventas_stock_estado CHECK (estado IN ('REGISTRADA','ANULADA')),
    CONSTRAINT uq_ventas_stock_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_ventas_stock_reversal UNIQUE (reversal_idempotency_key),
    CONSTRAINT fk_ventas_stock_alumno FOREIGN KEY (alumno_id) REFERENCES public.alumnos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_stock_stock FOREIGN KEY (stock_id) REFERENCES public.stocks(id) ON DELETE RESTRICT
);

CREATE INDEX ix_ventas_stock_alumno_fecha ON public.ventas_stock (alumno_id, fecha);
CREATE INDEX ix_ventas_stock_stock ON public.ventas_stock (stock_id);

CREATE TABLE public.cargos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    importe_original NUMERIC(19,2) NOT NULL,
    fecha_emision DATE NOT NULL,
    fecha_vencimiento DATE NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'PENDIENTE',
    mensualidad_id BIGINT,
    matricula_id BIGINT,
    concepto_id BIGINT,
    venta_stock_id BIGINT,
    cargo_origen_id BIGINT,
    idempotency_key VARCHAR(100),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cargos_importe CHECK (importe_original >= 0),
    CONSTRAINT ck_cargos_tipo CHECK (tipo IN ('MENSUALIDAD','MATRICULA','CONCEPTO','VENTA_STOCK','RECARGO')),
    CONSTRAINT ck_cargos_estado CHECK (estado IN ('PENDIENTE','PARCIAL','PAGADO','ANULADO')),
    CONSTRAINT ck_cargos_origen CHECK (
        (tipo = 'MENSUALIDAD' AND mensualidad_id IS NOT NULL AND matricula_id IS NULL AND concepto_id IS NULL AND venta_stock_id IS NULL AND cargo_origen_id IS NULL) OR
        (tipo = 'MATRICULA' AND mensualidad_id IS NULL AND matricula_id IS NOT NULL AND concepto_id IS NULL AND venta_stock_id IS NULL AND cargo_origen_id IS NULL) OR
        (tipo = 'CONCEPTO' AND mensualidad_id IS NULL AND matricula_id IS NULL AND concepto_id IS NOT NULL AND venta_stock_id IS NULL AND cargo_origen_id IS NULL) OR
        (tipo = 'VENTA_STOCK' AND mensualidad_id IS NULL AND matricula_id IS NULL AND concepto_id IS NULL AND venta_stock_id IS NOT NULL AND cargo_origen_id IS NULL) OR
        (tipo = 'RECARGO' AND mensualidad_id IS NULL AND matricula_id IS NULL AND concepto_id IS NULL AND venta_stock_id IS NULL AND cargo_origen_id IS NOT NULL)
    ),
    CONSTRAINT uq_cargos_mensualidad UNIQUE (mensualidad_id),
    CONSTRAINT uq_cargos_matricula UNIQUE (matricula_id),
    CONSTRAINT uq_cargos_venta_stock UNIQUE (venta_stock_id),
    CONSTRAINT uq_cargos_idempotency UNIQUE (idempotency_key),
    CONSTRAINT fk_cargos_alumno FOREIGN KEY (alumno_id) REFERENCES public.alumnos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cargos_mensualidad FOREIGN KEY (mensualidad_id) REFERENCES public.mensualidades(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cargos_matricula FOREIGN KEY (matricula_id) REFERENCES public.matriculas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cargos_concepto FOREIGN KEY (concepto_id) REFERENCES public.conceptos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cargos_venta_stock FOREIGN KEY (venta_stock_id) REFERENCES public.ventas_stock(id) ON DELETE RESTRICT
    ,CONSTRAINT fk_cargos_cargo_origen FOREIGN KEY (cargo_origen_id) REFERENCES public.cargos(id) ON DELETE RESTRICT
);

CREATE INDEX ix_cargos_alumno_estado_vencimiento
    ON public.cargos (alumno_id, estado, fecha_vencimiento);
CREATE INDEX ix_cargos_pendientes
    ON public.cargos (fecha_vencimiento, alumno_id) WHERE estado IN ('PENDIENTE','PARCIAL');
CREATE INDEX ix_cargos_concepto ON public.cargos (concepto_id);
CREATE INDEX ix_cargos_cargo_origen ON public.cargos (cargo_origen_id);

CREATE TABLE public.pagos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL,
    metodo_pago_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    monto_recibido NUMERIC(19,2) NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'REGISTRADO',
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    reversal_idempotency_key VARCHAR(100),
    observaciones VARCHAR(500),
    motivo_anulacion VARCHAR(500),
    fecha_anulacion TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_pagos_monto CHECK (monto_recibido > 0),
    CONSTRAINT ck_pagos_estado CHECK (estado IN ('REGISTRADO','ANULADO')),
    CONSTRAINT ck_pagos_anulacion CHECK ((estado = 'REGISTRADO' AND fecha_anulacion IS NULL AND motivo_anulacion IS NULL) OR (estado = 'ANULADO' AND fecha_anulacion IS NOT NULL AND motivo_anulacion IS NOT NULL)),
    CONSTRAINT uq_pagos_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_pagos_reversal_idempotency UNIQUE (reversal_idempotency_key),
    CONSTRAINT fk_pagos_alumno FOREIGN KEY (alumno_id) REFERENCES public.alumnos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pagos_metodo FOREIGN KEY (metodo_pago_id) REFERENCES public.metodo_pagos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_pagos_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_pagos_alumno_fecha ON public.pagos (alumno_id, fecha DESC);
CREATE INDEX ix_pagos_metodo ON public.pagos (metodo_pago_id);
CREATE INDEX ix_pagos_usuario ON public.pagos (usuario_id);

CREATE TABLE public.aplicaciones_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL,
    cargo_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    importe_aplicado NUMERIC(19,2) NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'APLICADA',
    fecha DATE NOT NULL,
    motivo_reversion VARCHAR(500),
    fecha_reversion TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_aplicaciones_importe CHECK (importe_aplicado > 0),
    CONSTRAINT ck_aplicaciones_estado CHECK (estado IN ('APLICADA','REVERTIDA')),
    CONSTRAINT ck_aplicaciones_reversion CHECK ((estado = 'APLICADA' AND fecha_reversion IS NULL AND motivo_reversion IS NULL) OR (estado = 'REVERTIDA' AND fecha_reversion IS NOT NULL AND motivo_reversion IS NOT NULL)),
    CONSTRAINT uq_aplicaciones_pago_cargo UNIQUE (pago_id, cargo_id),
    CONSTRAINT fk_aplicaciones_pago FOREIGN KEY (pago_id) REFERENCES public.pagos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_aplicaciones_cargo FOREIGN KEY (cargo_id) REFERENCES public.cargos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_aplicaciones_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_aplicaciones_cargo_estado ON public.aplicaciones_pago (cargo_id, estado);
CREATE INDEX ix_aplicaciones_pago_estado ON public.aplicaciones_pago (pago_id, estado);
CREATE INDEX ix_aplicaciones_usuario ON public.aplicaciones_pago (usuario_id);

CREATE TABLE public.egresos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    monto NUMERIC(19,2) NOT NULL,
    observaciones VARCHAR(500),
    metodo_pago_id BIGINT NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'REGISTRADO',
    usuario_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    reversal_idempotency_key VARCHAR(100),
    motivo_anulacion VARCHAR(500),
    fecha_anulacion TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_egresos_monto CHECK (monto > 0),
    CONSTRAINT ck_egresos_estado CHECK (estado IN ('REGISTRADO','ANULADO')),
    CONSTRAINT ck_egresos_anulacion CHECK ((estado = 'REGISTRADO' AND fecha_anulacion IS NULL AND motivo_anulacion IS NULL) OR (estado = 'ANULADO' AND fecha_anulacion IS NOT NULL AND motivo_anulacion IS NOT NULL)),
    CONSTRAINT uq_egresos_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_egresos_reversal UNIQUE (reversal_idempotency_key),
    CONSTRAINT fk_egresos_metodo FOREIGN KEY (metodo_pago_id) REFERENCES public.metodo_pagos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_egresos_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_egresos_fecha_metodo ON public.egresos (fecha, metodo_pago_id);
CREATE INDEX ix_egresos_metodo ON public.egresos (metodo_pago_id);
CREATE INDEX ix_egresos_usuario ON public.egresos (usuario_id);

CREATE TABLE public.movimientos_caja (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(15) NOT NULL,
    fecha DATE NOT NULL,
    importe NUMERIC(19,2) NOT NULL,
    metodo_pago_id BIGINT NOT NULL,
    pago_id BIGINT,
    egreso_id BIGINT,
    movimiento_revertido_id BIGINT,
    usuario_id BIGINT NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    motivo VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_movimientos_caja_tipo CHECK (tipo IN ('INGRESO_PAGO','EGRESO','REVERSO','AJUSTE_INGRESO','AJUSTE_EGRESO')),
    CONSTRAINT ck_movimientos_caja_importe CHECK (importe > 0),
    CONSTRAINT ck_movimientos_caja_origen CHECK (
        (tipo = 'INGRESO_PAGO' AND pago_id IS NOT NULL AND egreso_id IS NULL AND movimiento_revertido_id IS NULL) OR
        (tipo = 'EGRESO' AND pago_id IS NULL AND egreso_id IS NOT NULL AND movimiento_revertido_id IS NULL) OR
        (tipo = 'REVERSO' AND movimiento_revertido_id IS NOT NULL) OR
        (tipo IN ('AJUSTE_INGRESO','AJUSTE_EGRESO') AND pago_id IS NULL AND egreso_id IS NULL AND movimiento_revertido_id IS NULL AND motivo IS NOT NULL)
    ),
    CONSTRAINT uq_movimientos_caja_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_movimientos_caja_reversion UNIQUE (movimiento_revertido_id),
    CONSTRAINT fk_movimientos_caja_metodo FOREIGN KEY (metodo_pago_id) REFERENCES public.metodo_pagos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_caja_pago FOREIGN KEY (pago_id) REFERENCES public.pagos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_caja_egreso FOREIGN KEY (egreso_id) REFERENCES public.egresos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_caja_revertido FOREIGN KEY (movimiento_revertido_id) REFERENCES public.movimientos_caja(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_caja_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_movimientos_caja_fecha_metodo ON public.movimientos_caja (fecha, metodo_pago_id);
CREATE INDEX ix_movimientos_caja_metodo ON public.movimientos_caja (metodo_pago_id);
CREATE INDEX ix_movimientos_caja_pago ON public.movimientos_caja (pago_id);
CREATE INDEX ix_movimientos_caja_egreso ON public.movimientos_caja (egreso_id);
CREATE INDEX ix_movimientos_caja_usuario ON public.movimientos_caja (usuario_id);

CREATE TABLE public.movimientos_credito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id BIGINT NOT NULL,
    tipo VARCHAR(15) NOT NULL,
    importe NUMERIC(19,2) NOT NULL,
    pago_id BIGINT,
    cargo_id BIGINT,
    movimiento_revertido_id BIGINT,
    usuario_id BIGINT NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    motivo VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_movimientos_credito_tipo CHECK (tipo IN ('GENERACION','CONSUMO','REVERSO','AJUSTE_CREDITO','AJUSTE_DEBITO')),
    CONSTRAINT ck_movimientos_credito_importe CHECK (importe > 0),
    CONSTRAINT ck_movimientos_credito_origen CHECK (
        (tipo = 'GENERACION' AND pago_id IS NOT NULL AND cargo_id IS NULL AND movimiento_revertido_id IS NULL) OR
        (tipo = 'CONSUMO' AND pago_id IS NULL AND cargo_id IS NOT NULL AND movimiento_revertido_id IS NULL) OR
        (tipo = 'REVERSO' AND pago_id IS NULL AND cargo_id IS NULL AND movimiento_revertido_id IS NOT NULL) OR
        (tipo IN ('AJUSTE_CREDITO','AJUSTE_DEBITO') AND pago_id IS NULL AND cargo_id IS NULL
            AND movimiento_revertido_id IS NULL AND motivo IS NOT NULL)
    ),
    CONSTRAINT uq_movimientos_credito_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_movimientos_credito_reversion UNIQUE (movimiento_revertido_id),
    CONSTRAINT fk_movimientos_credito_alumno FOREIGN KEY (alumno_id) REFERENCES public.alumnos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_credito_pago FOREIGN KEY (pago_id) REFERENCES public.pagos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_credito_cargo FOREIGN KEY (cargo_id) REFERENCES public.cargos(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_credito_revertido FOREIGN KEY (movimiento_revertido_id) REFERENCES public.movimientos_credito(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_credito_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_movimientos_credito_alumno_fecha ON public.movimientos_credito (alumno_id, created_at);
CREATE INDEX ix_movimientos_credito_pago ON public.movimientos_credito (pago_id);
CREATE INDEX ix_movimientos_credito_cargo ON public.movimientos_credito (cargo_id);
CREATE INDEX ix_movimientos_credito_usuario ON public.movimientos_credito (usuario_id);

CREATE TABLE public.movimientos_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL,
    tipo VARCHAR(16) NOT NULL,
    cantidad INTEGER NOT NULL,
    venta_stock_id BIGINT,
    movimiento_revertido_id BIGINT,
    usuario_id BIGINT NOT NULL,
    idempotency_key VARCHAR(120) NOT NULL,
    motivo VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_movimientos_stock_tipo CHECK (tipo IN ('INGRESO','VENTA','REVERSO','AJUSTE_POSITIVO','AJUSTE_NEGATIVO')),
    CONSTRAINT ck_movimientos_stock_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_movimientos_stock_origen CHECK (
        (tipo = 'VENTA' AND venta_stock_id IS NOT NULL AND movimiento_revertido_id IS NULL) OR
        (tipo = 'REVERSO' AND movimiento_revertido_id IS NOT NULL) OR
        (tipo IN ('INGRESO','AJUSTE_POSITIVO','AJUSTE_NEGATIVO') AND venta_stock_id IS NULL AND movimiento_revertido_id IS NULL AND motivo IS NOT NULL)
    ),
    CONSTRAINT uq_movimientos_stock_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_movimientos_stock_reversion UNIQUE (movimiento_revertido_id),
    CONSTRAINT fk_movimientos_stock_stock FOREIGN KEY (stock_id) REFERENCES public.stocks(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_stock_venta FOREIGN KEY (venta_stock_id) REFERENCES public.ventas_stock(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_stock_revertido FOREIGN KEY (movimiento_revertido_id) REFERENCES public.movimientos_stock(id) ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_stock_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_movimientos_stock_stock_fecha ON public.movimientos_stock (stock_id, created_at);
CREATE INDEX ix_movimientos_stock_venta ON public.movimientos_stock (venta_stock_id);
CREATE INDEX ix_movimientos_stock_usuario ON public.movimientos_stock (usuario_id);

CREATE TABLE public.recibos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'PENDIENTE',
    storage_key VARCHAR(500),
    intentos INTEGER NOT NULL DEFAULT 0,
    ultimo_error VARCHAR(500),
    generado_at TIMESTAMPTZ,
    enviado_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_recibos_estado CHECK (estado IN ('PENDIENTE','GENERADO','ENVIADO','ERROR')),
    CONSTRAINT ck_recibos_intentos CHECK (intentos >= 0),
    CONSTRAINT uq_recibos_pago UNIQUE (pago_id),
    CONSTRAINT fk_recibos_pago FOREIGN KEY (pago_id) REFERENCES public.pagos(id) ON DELETE RESTRICT
);

CREATE TABLE public.recibos_pendientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'PENDIENTE',
    intentos INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimo_error VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    CONSTRAINT ck_recibos_pendientes_tipo CHECK (tipo IN ('GENERAR_Y_ENVIAR')),
    CONSTRAINT ck_recibos_pendientes_estado CHECK (estado IN ('PENDIENTE','PROCESANDO','COMPLETADO','ERROR')),
    CONSTRAINT ck_recibos_pendientes_intentos CHECK (intentos >= 0),
    CONSTRAINT uq_recibos_pendientes_pago_tipo UNIQUE (pago_id, tipo),
    CONSTRAINT fk_recibos_pendientes_pago FOREIGN KEY (pago_id) REFERENCES public.pagos(id) ON DELETE RESTRICT
);

CREATE INDEX ix_recibos_pendientes_worker
    ON public.recibos_pendientes (estado, next_attempt_at);

CREATE TABLE public.notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    tipo VARCHAR(50) NOT NULL,
    mensaje VARCHAR(500) NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL,
    fecha_negocio DATE NOT NULL,
    dedup_key VARCHAR(100) NOT NULL,
    leida BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_notificaciones_dedup UNIQUE (dedup_key),
    CONSTRAINT fk_notificaciones_usuario FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id) ON DELETE RESTRICT
);

CREATE INDEX ix_notificaciones_usuario_leida
    ON public.notificaciones (usuario_id, leida, fecha_creacion DESC);

INSERT INTO public.roles (descripcion, activo)
VALUES ('ADMINISTRADOR', TRUE);
