name: CI/CD - Deploy LE Dance

on:
  push:
    branches:
      - main  # Ajusta la rama según convenga

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Build del Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependencias (Frontend)
        working-directory: frontend
        run: npm install

      - name: Construir Frontend
        working-directory: frontend
        run: npm run build

      # 3. Build del Backend (Maven con Corretto 17)
      - name: Setup Java (Corretto 17)
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

      - name: Construir Backend con Maven
        working-directory: backend
        run: mvn clean package

      # 4. Despliegue: Copiar artefactos al VPS
      - name: Copiar Frontend al VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "frontend/dist/*"
          target: "/home/jeremias/le-dance/frontend/dist/"

      - name: Copiar Backend al VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "backend/target/backend-1.0.jar"
          target: "/home/jeremias/le-dance/backend/"

      # 5. Reiniciar el backend en el VPS usando PM2
      - name: Reiniciar backend en VPS con pm2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Aseguramos que el PATH incluya la ubicación de PM2 instalado vía nvm
            export PATH=$PATH:/root/.nvm/versions/node/v22.13.1/bin
            # Se intenta detener el proceso actual del backend (si existe)
            pm2 delete le-dance-backend || true
            # Inicia el backend con PM2 usando el JAR copiado
            pm2 start "java -jar /home/jeremias/le-dance/backend/target/backend-1.0.jar" --name le-dance-backend
            # Guarda la configuración de PM2 para reinicios automáticos
            pm2 save
            exit 0
