name: CI/CD - Deploy LE Dance

on:
  push:
    branches:
      - main  # Ajusta la rama según convenga

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configurar Docker
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Construir y subir imágenes a Docker Hub
      - name: Build y Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/le-dance-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/le-dance-backend:latest

      - name: Build y Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/le-dance-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/le-dance-frontend:latest

      # 4️⃣ Desplegar en el VPS
      - name: Copiar archivos Docker Compose al VPS
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "docker-compose.yml"
          target: "/home/jeremias/le-dance/"

      - name: Reiniciar contenedores en el VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/jeremias/le-dance
            docker-compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/le-dance-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/le-dance-frontend:latest
            docker-compose up -d
